# Generated by Django 5.2.8 on 2025-11-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENTREGA',
            fields=[
                ('idEntrega', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DOMICILIO', 'DOMICILIO')], max_length=20)),
                ('direccionEntr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('idUsuario', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('nombreU', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidoP', models.CharField(max_length=60)),
                ('apellidoM', models.CharField(blank=True, max_length=60, null=True)),
                ('fechaN', models.DateField()),
                ('celular', models.CharField(max_length=20)),
                ('puntosReco', models.IntegerField(default=0)),
                ('saldoEqui', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CARRITO',
            fields=[
                ('idCarrito', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fechaE', models.DateField(blank=True, null=True)),
                ('horaE', models.TimeField(blank=True, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='pasteleria.entrega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='pasteleria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ORDEN',
            fields=[
                ('idOrden', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='pasteleria.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='pasteleria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PAN',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PASTEL',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('relleno', models.CharField(max_length=20)),
                ('sabor', models.CharField(max_length=20)),
                ('decoracion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='POSTRE',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TARTA',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('tamaño', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE',
            fields=[
                ('idItem', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pasteleria.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pasteleria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PROMOCION',
            fields=[
                ('idPromocion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigencia', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], max_length=20)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promocion', to='pasteleria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TICKET',
            fields=[
                ('idTicket', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('formaPago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('status', models.CharField(choices=[('ENTREGADO', 'Entregado'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='pasteleria.orden')),
            ],
        ),
    ]
