# Generated by Django 5.2.8 on 2025-11-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('PASTEL', 'Pastel'), ('TARTA', 'Tarta'), ('POSTRE', 'Postre'), ('PAN', 'Pan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PROMOCION',
            fields=[
                ('idPromocion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigencia', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('idUsuario', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('nombreU', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidoP', models.CharField(max_length=60)),
                ('apellidoM', models.CharField(blank=True, max_length=60, null=True)),
                ('fechaN', models.DateField()),
                ('celular', models.CharField(max_length=20)),
                ('puntosReco', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PASTEL',
            fields=[
                ('producto', models.OneToOneField(limit_choices_to={'tipo': 'PASTEL'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('relleno', models.CharField(max_length=20)),
                ('sabor', models.CharField(max_length=20)),
                ('decoracion', models.CharField(max_length=20)),
                ('tamaño', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PEDIDO',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
                ('horaEntrega', models.TimeField(blank=True, null=True)),
                ('direccionEntrega', models.CharField(blank=True, max_length=35, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipoEntrega', models.CharField(choices=[('PICKUP', 'pickup'), ('DOMICILIO', 'domicilio')], max_length=20)),
                ('formaPago', models.CharField(choices=[('MERCADOPAGO', 'mercadopago'), ('TARJETA', 'tarjeta')], max_length=20)),
                ('status', models.CharField(choices=[('RECIBIDO', 'Pedido Recibido'), ('ELABORANDO', 'En proceso de elaboración'), ('LISTO', 'Listo para entrega'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pasteleria.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pasteleria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE',
            fields=[
                ('idItem', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pasteleria.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pasteleria.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto', to='pasteleria.promocion'),
        ),
    ]
